# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0002_auto_20171013_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='junitreport',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
