# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0003_add_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUnitSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('runtime', models.FloatField()),
                ('skipped', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junit_reporting.JUnitReport')),
            ],
        ),
    ]
