# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0005_add_JUnitTest'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUnitProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Error'), ('F', 'Failure')], default='F', max_length=2)),
                ('message', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junit_reporting.JUnitTest')),
            ],
        ),
    ]
