# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0007_update_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUnitProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('repo_url', models.URLField()),
                ('ci_url_pattern', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'JUnit Project',
            },
        ),
        migrations.AddField(
            model_name='junitreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='junit_reporting.JUnitProject'),
        ),
    ]
