# -*- coding: utf-8 -*-
# pylint: disable=invalid-name,missing-docstring
# Generated by Django 1.11.6 on 2017-10-14 14:57
from __future__ import unicode_literals

from django.db import migrations


# pylint: disable=unused-argument
def create_wildcard_project(apps, schema_editor):
    JUnitProject = apps.get_model('junit_reporting', 'JUnitProject')
    JUnitProject.objects.create(name='_', repo_url='', ci_url_pattern='')


# pylint: disable=unused-argument
def assign_wildcard_project(apps, schema_editor):
    JUnitProject = apps.get_model('junit_reporting', 'JUnitProject')
    wildcard = JUnitProject.objects.get(name='_')
    JUnitReport = apps.get_model('junit_reporting', 'JUnitReport')
    for report in JUnitReport.objects.all().filter(project__isnull=True):
        report.project = wildcard
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0008_add_JUnitProject'),
    ]

    operations = [
        migrations.RunPython(create_wildcard_project),
        migrations.RunPython(assign_wildcard_project),
    ]
