# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0009_wildcard_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junitreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junit_reporting.JUnitProject'),
        ),
    ]
