# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junit_reporting', '0010_JUnitReport_project_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junitreport',
            name='build_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='junitreport',
            unique_together=set([('build_number', 'project')]),
        ),
    ]
